## NumPy简介  
NumPy是一个中队多为数组（Ndarray）的科学计算包，这个包封装了多个可以用于数组间计算的函数，可以直接使用。  
数组是一个系统数据类型元素按照一定顺序排列组合，需要注意的是必须**相同数据类型**。

## NumPy数组的生成

### 生成一般数组

- 给array()函数传入一个列表

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

- 给array()函数传入一个元组

In [4]:
arr = np.array((2,4,6,8))
arr

array([2, 4, 6, 8])

- 给array()函数传入一个嵌套列表

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

### 生成特殊类型数组

- 生成固定范围的随机数组  
使用arange()函数  
np.arange(start,stop,step)  
以start开始(包括这个值)，stop结束(不包括这个值)，step为步长

In [7]:
#以1开始15为结束，步长为3的随机序列
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

当sep不写时，步长默认为1：

In [8]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**当start不写时，默认从0开始**

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**生成指定形状全为0的数组**  
生成指定形状全为0的数组要用到zeros()函数

In [10]:
#生成长度为3的0数组
np.zeros(3)

array([0., 0., 0.])

In [13]:
#生成2行3列的数组
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**生成制定形状全为1的数组**  
用ones()函数，使用方法和zeros()函数类似

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**生成一个正方形单位矩阵**  
单位矩阵就是对教学的元素值全为1，其余位置元素值全为0，用eye()函数  
eye()函数需要在括号中指明正方形边长

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 生成随机数组  
随机数组生成主要用到NumPy中的random模块

**np.random.rand()方法**  
np.random.rand()方法主要用于生成（0，1）之间的随机数组  
当给rand()函数传入具体值时，生成一个相应长度值且值位于(0,1)之间的随机数组

In [18]:
np.random.rand()

0.7475725418820932

In [19]:
np.random.rand(3)

array([0.94535405, 0.65689305, 0.76253242])

In [21]:
#生成2行3列值位于(0,1)之间的数组
np.random.rand(2,3)

array([[0.56619521, 0.03551248, 0.92040938],
       [0.08416216, 0.86372162, 0.34272074]])

**np.random.randn()方法**  
用来生成满足正态分布的指定形状数组  
当传入一个具体值时，生成相应长度满足正态分布的随机数组

In [22]:
np.random.randn(3)

array([ 0.51163337,  0.87618008, -0.56117356])

In [23]:
np.random.randn(2,3)

array([[ 0.87253144,  0.05644238, -2.41286612],
       [-2.05235295,  0.68378704,  0.12462664]])

**np.random.randint()方法**  
与np.arange()方法类似，用于生成一定范围内的随机数组  
np.random.randint(low,high= None,size = None)  
在左闭右开区间[low,high)生成数组大小为size的均匀分布的整数值

In [24]:
np.random.randint(1,5,10)

array([4, 2, 2, 4, 2, 1, 4, 4, 1, 1])

输出[low,high)之间的整数

In [5]:
import numpy as np
np.random.randint(5,10)

8

生成[0,5)10个元素的数组

In [3]:
import numpy as np
np.random.randint(5,size=10)

array([0, 2, 2, 3, 0, 1, 1, 0, 2, 3])

low=1,输入[0,1)之间的整数

In [34]:
np.random.randint(1)

0

low=5，high=None，size=（2，3）2行3列，输出范围[0,5)之间的整数

In [35]:
np.random.randint(5,size=(2,3))

array([[0, 3, 2],
       [4, 2, 4]])

**np.random.choice()方法**  
主要用来从已知数组中随机选取相应大小的数组  
np.random.choiice(a,size=None,replace=None,p=None)  
从数组a中选取size大小作为一个数组作为新的数组，a可以是一个数组，也可以是一个整数  
当a是一个数组时表示从该数组中随机采样  
当a为整数是，表示从range(int)中采样

In [38]:
#从整数a中随机选取3个值组成一个新的数组
np.random.choice(5,3)
a = np.array([1,4,6,7,8,9,])
np.random.choice(a,3)

array([9, 9, 1])

In [40]:
#从整数a中随机选取2行3列数值组成一个新的数组
np.random.choice(5,(2,3))

array([[4, 1, 4],
       [0, 1, 0]])

**np.random.shuffle()方法**  
主用用来将原数组顺序打乱

In [46]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.random.shuffle(arr)
arr

array([3, 4, 9, 7, 2, 6, 0, 8, 5, 1])

## NumPy数组的基本属性  
NumPy数组的基本属性包括数组的形状、大小、类型和维数。

**数组的形状**

In [50]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
arr.shape

(3, 3)

**数组的大小**

In [51]:
arr.size

9

**数组的类型**

In [53]:
arr.dtype

dtype('int32')

**数组的维数**

In [54]:
arr.ndim

2